In [201]:
%pip install xgboost

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Python310\\xgboost'
Consider using the `--user` option or check the permissions.



In [295]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sn
import sklearn
from sklearn.linear_model import RidgeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
import numpy as np
from sklearn import preprocessing
from sklearn import metrics
import xgboost as xgb

In [296]:
train = pd.read_csv('train.csv')
train.shape

(76020, 371)

In [221]:
train.head(10)

ID  var3  var15  imp_ent_var16_ult1  imp_op_var39_comer_ult1  \
0   1     2     23                 0.0                      0.0   
1   3     2     34                 0.0                      0.0   
2   4     2     23                 0.0                      0.0   
3   8     2     37                 0.0                    195.0   
4  10     2     39                 0.0                      0.0   
5  13     2     23                 0.0                      0.0   
6  14     2     27                 0.0                      0.0   
7  18     2     26                 0.0                      0.0   
8  20     2     45                 0.0                      0.0   
9  23     2     25                 0.0                      0.0   

   imp_op_var39_comer_ult3  imp_op_var40_comer_ult1  imp_op_var40_comer_ult3  \
0                      0.0                      0.0                      0.0   
1                      0.0                      0.0                      0.0   
2                      0.0                      0.0                      0.0   
3                    195.0                      0.0                      0.0   
4                      0.0                      0.0                      0.0   
5                      0.0                      0.0                      0.0   
6                      0.0                      0.0                      0.0   
7                      0.0                      0.0                      0.0   
8                      0.0                      0.0                      0.0   
9                      0.0                      0.0                      0.0   

   imp_op_var40_efect_ult1  imp_op_var40_efect_ult3  ...  \
0                      0.0                      0.0  ...   
1                      0.0                      0.0  ...   
2                      0.0                      0.0  ...   
3                      0.0                      0.0  ...   
4                      0.0                      0.0  ...   
5                      0.0                      0.0  ...   
6                      0.0                      0.0  ...   
7                      0.0                      0.0  ...   
8                      0.0                      0.0  ...   
9                      0.0                      0.0  ...   

   saldo_medio_var33_hace2  saldo_medio_var33_hace3  saldo_medio_var33_ult1  \
0                      0.0                      0.0                     0.0   
1                      0.0                      0.0                     0.0   
2                      0.0                      0.0                     0.0   
3                      0.0                      0.0                     0.0   
4                      0.0                      0.0                     0.0   
5                      0.0                      0.0                     0.0   
6                      0.0                      0.0                     0.0   
7                      0.0                      0.0                     0.0   
8                      0.0                      0.0                     0.0   
9                      0.0                      0.0                     0.0   

   saldo_medio_var33_ult3  saldo_medio_var44_hace2  saldo_medio_var44_hace3  \
0                     0.0                      0.0                      0.0   
1                     0.0                      0.0                      0.0   
2                     0.0                      0.0                      0.0   
3                     0.0                      0.0                      0.0   
4                     0.0                      0.0                      0.0   
5                     0.0                      0.0                      0.0   
6                     0.0                      0.0                      0.0   
7                     0.0                      0.0                      0.0   
8                     0.0                      0.0                      0.0   
9                     0.0                      0.0             

In [297]:
train['TARGET'].value_counts()

0    73012
1     3008
Name: TARGET, dtype: int64

In [54]:
train.describe()

ID           var3         var15  imp_ent_var16_ult1  \
count   76020.000000   76020.000000  76020.000000        76020.000000   
mean    75964.050723   -1523.199277     33.212865           86.208265   
std     43781.947379   39033.462364     12.956486         1614.757313   
min         1.000000 -999999.000000      5.000000            0.000000   
25%     38104.750000       2.000000     23.000000            0.000000   
50%     76043.000000       2.000000     28.000000            0.000000   
75%    113748.750000       2.000000     40.000000            0.000000   
max    151838.000000     238.000000    105.000000       210000.000000   

       imp_op_var39_comer_ult1  imp_op_var39_comer_ult3  \
count             76020.000000             76020.000000   
mean                 72.363067               119.529632   
std                 339.315831               546.266294   
min                   0.000000                 0.000000   
25%                   0.000000                 0.000000   
50%                   0.000000                 0.000000   
75%                   0.000000                 0.000000   
max               12888.030000             21024.810000   

       imp_op_var40_comer_ult1  imp_op_var40_comer_ult3  \
count             76020.000000             76020.000000   
mean                  3.559130                 6.472698   
std                  93.155749               153.737066   
min                   0.000000                 0.000000   
25%                   0.000000                 0.000000   
50%                   0.000000                 0.000000   
75%                   0.000000                 0.000000   
max                8237.820000             11073.570000   

       imp_op_var40_efect_ult1  imp_op_var40_efect_ult3  ...  \
count             76020.000000             76020.000000  ...   
mean                  0.412946                 0.567352  ...   
std                  30.604864                36.513513  ...   
min                   0.000000                 0.000000  ...   
25%                   0.000000                 0.000000  ...   
50%                   0.000000                 0.000000  ...   
75%                   0.000000                 0.000000  ...   
max                6600.000000              6600.000000  ...   

       saldo_medio_var33_hace2  saldo_medio_var33_hace3  \
count             76020.000000             76020.000000   
mean                  7.935824                 1.365146   
std                 455.887218               113.959637   
min                   0.000000                 0.000000   
25%                   0.000000                 0.000000   
50%                   0.000000                 0.000000   
75%                   0.000000                 0.000000   
max               50003.880000             20385.720000   

       saldo_medio_var33_ult1  saldo_medio_var33_ult3  \
count            76020.000000            76020.000000   
mean                12.215580                8.784074   
std                783.207399              538.439211   
min                  0.000000                0.000000   
25%                  0.000000                0.000000   
50%                  0.000000                0.000000   
75%                  0.000000                0.000000   
max             138831.630000            91778.730000   

       saldo_medio_var44_hace2  saldo_medio_var44_hace3  \
count             76020.000000             76020.000000   
mean                 31.505324                 1.858575   
std                2013.125393               147.786584   
min                   0.000000                 0.000000   
25%                   0.000000                 0.000000   
50%                   0.000000                 0.000000   
75%                   0.000000                 0.000000   
max              438329.220000             24650.010000   

       saldo_medio_var44_ult1  saldo_medio_var44_ult3         var38  \
count            76020.000000            76020.000000  7.602000e+04   

Remove colunas com apenas um valor

In [301]:
dropped_col = []
for col in train.columns:
    if len(train[col].unique())==1:
        train.drop(col,inplace=True,axis=1)
        dropped_col.append(col)
dropped_col
train.shape

(71213, 337)

Remove colunas repetidas, ignorando a coluna ID

In [302]:
train.drop(train[train.drop(columns='ID').duplicated()].index,inplace=True)
train.shape
#drop_duplicates(keep='first',inplace=True)

(71213, 337)

Removendo colunas com alta correlação

In [303]:
corr = train.corr(method='pearson')

In [304]:
upper_tri = corr.where(np.triu(np.ones(corr.shape),k=1).astype(np.bool))
to_drop = [column for column in upper_tri if any (upper_tri[column]>0.9)]
train.drop(columns=to_drop,inplace=True,axis=1)
dropped_col += to_drop
train.shape

C:\Users\lucas\AppData\Local\Temp/ipykernel_13232/43705554.py:1: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  upper_tri = corr.where(np.triu(np.ones(corr.shape),k=1).astype(np.bool))


(71213, 171)

In [293]:
corr_2=train.corr().abs()['TARGET']
corr_2

ID                         0.001107
var3                       0.004146
var15                      0.097508
imp_ent_var16_ult1         0.000007
imp_op_var39_comer_ult1    0.010763
                             ...   
saldo_medio_var44_hace3    0.002636
saldo_medio_var44_ult1     0.003204
saldo_medio_var44_ult3     0.003112
var38                      0.020117
TARGET                     1.000000
Name: TARGET, Length: 337, dtype: float64

In [294]:
to_drop = [column for column in corr_2.keys() if (corr_2[column]<0.001)]
to_drop
train.drop(columns=to_drop,inplace=True,axis=1)
dropped_col +=to_drop
train.shape

(71213, 296)

 Upsample das amostras onde TARGET = 1. O objetivo é reduzir o bias em direção ao TARGET = 0 uma vez que no estado atual uma previsão 0 teria 96% de acerto

In [305]:
train1 = train[train['TARGET']==1]

In [306]:
train_upsampled = train1.sample(len(train[train['TARGET']==0]),replace=True).append(train[train['TARGET']==0])

In [307]:
train_upsampled['TARGET'].value_counts()

1    68398
0    68398
Name: TARGET, dtype: int64

In [308]:
scaler = preprocessing.StandardScaler().fit(train1.drop(columns=['TARGET','ID']))

In [309]:
X_train = scaler.transform(train_upsampled.drop(columns=['TARGET','ID']))
y_train = train_upsampled['TARGET']

## Ridge Classifier

In [310]:
clf_ridge = RidgeClassifier()

In [311]:
y_train = train_upsampled['TARGET']

In [312]:
clf_ridge.fit(X_train, y_train) #train the model

C:\Python310\lib\site-packages\sklearn\linear_model\_ridge.py:157: LinAlgWarning: Ill-conditioned matrix (rcond=1.51588e-22): result may not be accurate.
  return linalg.solve(A, Xy, sym_pos=True, overwrite_a=True).T


RidgeClassifier()

In [313]:
pred = clf_ridge.predict(train.drop(columns=['TARGET','ID']))

C:\Python310\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but RidgeClassifier was fitted without feature names
  warnings.warn(


In [314]:
metrics.accuracy_score(train['TARGET'],pred)

0.954418434836336

In [319]:
metrics.roc_auc_score(train['TARGET'],pred)

0.49838211072306554

In [315]:
np.count_nonzero(pred)

449

In [316]:
test = pd.read_csv('test.csv')

In [268]:
pred = clf_ridge.predict(train.drop(columns=['ID','TARGET']))

C:\Python310\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but RidgeClassifier was fitted without feature names
  warnings.warn(


In [269]:
pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [270]:
np.count_nonzero(pred)

449

In [271]:
metrics.confusion_matrix(train['TARGET'],pred)

array([[67774,   440],
       [ 2804,     9]], dtype=int64)

## RandomForestClassifier

In [320]:
clf_randomforest = RandomForestClassifier()

In [321]:
clf_randomforest.fit(X_train,y_train)

RandomForestClassifier()

In [274]:
pred_RF = clf_ridge.predict(train.drop(columns=['TARGET','ID']))

C:\Python310\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but RidgeClassifier was fitted without feature names
  warnings.warn(


In [275]:
metrics.accuracy_score(train['TARGET'],pred_RF)

0.9543272276739831

In [276]:
pred_RF

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [277]:
np.count_nonzero(pred_RF)

449

In [278]:
np.where(pred_RF == train['TARGET'],'ok',0 )

array(['ok', 'ok', 'ok', ..., 'ok', 'ok', 'ok'], dtype='<U11')

In [279]:
clf_randomforest.fit((train.drop(columns=['TARGET','ID'])),train['TARGET'])

RandomForestClassifier()

In [281]:
pred_RF = clf_ridge.predict(train.drop(columns=['TARGET','ID']))

C:\Python310\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but RidgeClassifier was fitted without feature names
  warnings.warn(


In [282]:
metrics.accuracy_score(train['TARGET'],pred_RF)

0.9543272276739831

In [283]:
metrics.confusion_matrix(train['TARGET'],pred_RF)

array([[67774,   440],
       [ 2804,     9]], dtype=int64)

In [286]:
import numpy as np
import pandas as pd
from xgboost.sklearn import XGBClassifier
from sklearn.model_selection import StratifiedKFold
from sklearn.decomposition import PCA
from sklearn.preprocessing import normalize
import xgboost as xgb
import csv

np.random.seed(1234)

df_train = pd.read_csv('train.csv')
df_test = pd.read_csv('test.csv')
labels = df_train['TARGET'].values
df_train = df_train.drop(['TARGET'], axis=1)
piv_train = df_train.shape[0]

#calc zero preds manually
ids_zero = list(df_test[df_test['var15']<23]['ID'].values)
df_test = df_test[df_test['var15']>=23]

ids_zero = ids_zero+list(df_test[df_test['saldo_medio_var5_hace2']>160000]['ID'].values)
df_test = df_test[df_test['saldo_medio_var5_hace2']<=160000]

ids_zero = ids_zero+list(df_test[df_test['saldo_var33']>0]['ID'].values)
df_test = df_test[df_test['saldo_var33']<=0]

ids_zero = ids_zero+list(df_test[df_test['var38']>3988596]['ID'].values)
df_test = df_test[df_test['var38']<=3988596]

df_test['NV']=df_test['num_var33']+df_test['saldo_medio_var33_ult3']+df_test['saldo_medio_var44_hace2']+df_test['saldo_medio_var44_hace3']+df_test['saldo_medio_var33_ult1']+df_test['saldo_medio_var44_ult1']
ids_zero = ids_zero+list(df_test[df_test['NV']>0]['ID'].values)
df_test = df_test[df_test['NV']<=0]

ids_zero = ids_zero+list(df_test[df_test['var21']>7500]['ID'].values)
df_test = df_test[df_test['var21']<=7500]

ids_zero = ids_zero+list(df_test[df_test['num_var30']>9]['ID'].values)
df_test = df_test[df_test['num_var30']<=9]

ids_zero = ids_zero+list(df_test[df_test['num_var13_0']>6]['ID'].values)
df_test = df_test[df_test['num_var13_0']<=6]

ids_zero = ids_zero+list(df_test[df_test['num_var33_0']>0]['ID'].values)
df_test = df_test[df_test['num_var33_0']<=0]

ids_zero = ids_zero+list(df_test[df_test['imp_ent_var16_ult1']>51003]['ID'].values)
df_test = df_test[df_test['imp_ent_var16_ult1']<=51003]

ids_zero = ids_zero+list(df_test[df_test['imp_op_var39_comer_ult3']>13184]['ID'].values)
df_test = df_test[df_test['imp_op_var39_comer_ult3']<=13184]

ids_zero = ids_zero+list(df_test[df_test['saldo_medio_var5_ult3']>108251]['ID'].values)
df_test = df_test[df_test['saldo_medio_var5_ult3']<=108251]

ids_zero = ids_zero+list(df_test[df_test['num_var37_0']>45]['ID'].values)
df_test = df_test[df_test['num_var37_0']<=45]

ids_zero = ids_zero+list(df_test[df_test['saldo_var5']>137615]['ID'].values)
df_test = df_test[df_test['saldo_var5']<=137615]

ids_zero = ids_zero+list(df_test[df_test['saldo_var8']>60099]['ID'].values)
df_test = df_test[df_test['saldo_var8']<=60099]

ids_zero = ids_zero+list(df_test[df_test['saldo_var12']>506414]['ID'].values)
df_test = df_test[df_test['saldo_var12']<=506414]

zero_preds = zip(ids_zero,[0]*len(ids_zero))

id_test = df_test['ID']

#limit vars in test based on min and max vals of train
for col in df_train.columns:
    minVal = np.min(df_train[col])
    maxVal = np.max(df_train[col])
    df_test[col] = [minVal if val<minVal else val for val in df_test[col]]
    df_test[col] = [maxVal if val>maxVal else val for val in df_test[col]]

#Creating a DataFrame with train+test data
df_all = pd.concat((df_train, df_test), axis=0, ignore_index=True)

#Removing id
df_all = df_all.drop(['ID'], axis=1)

#Remove constant features
df_all = df_all.drop(['saldo_var2_ult1','num_trasp_var17_out_hace3','num_var46','num_reemb_var13_hace3','num_var41','num_reemb_var33_hace3','num_var2_ult1','imp_reemb_var13_hace3','num_var2_0_ult1','imp_trasp_var33_out_hace3','imp_reemb_var33_hace3','ind_var46_0','ind_var27_0','saldo_var27','saldo_var28','imp_amort_var34_hace3','num_var46_0','num_var28_0','imp_trasp_var17_out_hace3','num_var27_0','ind_var27','ind_var28','ind_var2_0','ind_var28_0','num_var27','num_var28','num_trasp_var33_out_hace3','ind_var41','ind_var2','saldo_var46','saldo_var41','ind_var46'], axis=1)

#Remove identical features
features = df_all.columns
rows = df_all.shape[0]
cols_to_remove = []
for f1 in features:
    for f2 in features:
        if f1!=f2 and f1 not in cols_to_remove and f2 not in cols_to_remove and (df_all[f1]==df_all[f2]).astype(int).sum() == rows:
            #print f1, f2, 'are equals'
            cols_to_remove.append(f2)
#print cols_to_remove
df_all = df_all.drop(cols_to_remove, axis=1)

df_all['var38'] = df_all['var38'].map(np.log)

df_all['zeros'] = (df_all==0).astype(int).sum(1)

#Filling nan
df_all = df_all.fillna(-997)

vals = df_all.values
X = vals[:piv_train]
y = labels
X_test = vals[piv_train:]


xgb = XGBClassifier(max_depth=5, learning_rate=0.0202048, n_estimators=560, objective='binary:logistic', subsample=0.6815, colsample_bytree=0.701, seed=0)                
xgb.fit(X, y)
y_pred_xgb = xgb.predict_proba(X_test)
result = y_pred_xgb[:,1]
result = zip(id_test.values, result) #+zero_preds

#Generate submission
predictions_file = open("submission.csv", "w")
open_file_object = csv.writer(predictions_file)
open_file_object.writerow(['ID','TARGET'])
open_file_object.writerows(result)
predictions_file.close()

C:\Python310\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[07:51:53] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


In [323]:
xgb = XGBClassifier(max_depth=5, learning_rate=0.0202048, n_estimators=560, objective='binary:logistic', subsample=0.6815, colsample_bytree=0.701, seed=0)
xgb.fit(X_train,y_train)

C:\Python310\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[21:25:38] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=0.701,
              enable_categorical=False, gamma=0, gpu_id=-1,
              importance_type=None, interaction_constraints='',
              learning_rate=0.0202048, max_delta_step=0, max_depth=5,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=560, n_jobs=8, num_parallel_tree=1, predictor='auto',
              random_state=0, reg_alpha=0, reg_lambda=1, scale_pos_weight=1,
              seed=0, subsample=0.6815, tree_method='exact',
              validate_parameters=1, verbosity=None)

In [324]:
pred_xgb = xgb.predict(train.drop(columns=['TARGET','ID']))

In [326]:
metrics.confusion_matrix(train['TARGET'],pred_xgb)

array([[68398,     0],
       [ 2815,     0]], dtype=int64)

In [327]:
gbrt_clf = sklearn.ensemble.GradientBoostingClassifier(n_estimators=100,criterion='friedman_mse', random_state=121)

In [332]:
gbrt_clf.fit(X_train,y_train)
pred_gbrt = gbrt_clf.predict_proba(train.drop(columns=['TARGET','ID']))
metrics.roc_auc_score(train['TARGET'],pred_gbrt)

C:\Python310\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but GradientBoostingClassifier was fitted without feature names
  warnings.warn(


ValueError: y should be a 1d array, got an array of shape (71213, 2) instead.

In [333]:
pred_gbrt

array([[0.86853625, 0.13146375],
       [0.92440902, 0.07559098],
       [0.92148919, 0.07851081],
       ...,
       [0.89369097, 0.10630903],
       [0.92840238, 0.07159762],
       [0.92458268, 0.07541732]])